/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2fd0f9181a07adb6293292324dc9a1b3)
interface __BaseEnv_Env {
	RATE_LIMITER: RateLimit;
	GITHUB_REPO: "timmyagentic/cc-connect-next";
	GITHUB_LABEL: "user-feedback";
	GITHUB_APP_ID: "4781408";
	GITHUB_APP_INSTALLATION_ID: "157971931";
	GITHUB_APP_PRIVATE_KEY: string;
	FEEDBACK_REPORTS: DurableObjectNamespace<import("./src/worker").FeedbackReport>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "FeedbackReport";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_REPO" | "GITHUB_LABEL" | "GITHUB_APP_ID" | "GITHUB_APP_INSTALLATION_ID" | "GITHUB_APP_PRIVATE_KEY">> {}
}
